// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFLnZzd7yL4f53YsSrrcKCM8LEb3o3l1E',
    appId: '1:438579366577:web:fa8abfcf79a48fea23f090',
    messagingSenderId: '438579366577',
    projectId: 'grocerystore-8119d',
    authDomain: 'grocerystore-8119d.firebaseapp.com',
    storageBucket: 'grocerystore-8119d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbKvCbDD5Ds3p7W-8RoYOR52qtlpOtj8c',
    appId: '1:438579366577:android:2eb064e0eee58e3223f090',
    messagingSenderId: '438579366577',
    projectId: 'grocerystore-8119d',
    storageBucket: 'grocerystore-8119d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMn-CIa4ApCS4wLNE24DZLAKSjg2CfTdk',
    appId: '1:438579366577:ios:7ec04865dfe5970123f090',
    messagingSenderId: '438579366577',
    projectId: 'grocerystore-8119d',
    storageBucket: 'grocerystore-8119d.appspot.com',
    iosBundleId: 'com.example.sumiPrinter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMn-CIa4ApCS4wLNE24DZLAKSjg2CfTdk',
    appId: '1:438579366577:ios:7ec04865dfe5970123f090',
    messagingSenderId: '438579366577',
    projectId: 'grocerystore-8119d',
    storageBucket: 'grocerystore-8119d.appspot.com',
    iosBundleId: 'com.example.sumiPrinter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFLnZzd7yL4f53YsSrrcKCM8LEb3o3l1E',
    appId: '1:438579366577:web:085463beb55f48e423f090',
    messagingSenderId: '438579366577',
    projectId: 'grocerystore-8119d',
    authDomain: 'grocerystore-8119d.firebaseapp.com',
    storageBucket: 'grocerystore-8119d.appspot.com',
  );
}
